import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
    },
    activityView: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    subContainer: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(3),
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    profileConatiner: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(2),
      alignItems: 'center',
    },
    imgStyle: {
      backgroundColor: theme.color.dividerColor,
      width: wp(13),
      height: hp(8),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: hp(1.5),
      flexDirection: 'row',
    },
    workhistoryContainer: {
      height: hp(7),
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      marginTop: hp(1),
    },
    nameContainer: {
      justifyContent: 'flex-start',
      paddingLeft: wp(2),
    },
    aboutContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      paddingTop: hp(5),
      borderBottomWidth: hp(0.2),
      borderBottomColor: theme.color.dividerColor,
    },
    reviewContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      paddingRight: hp(2),

      marginVertical: hp(1),
    },
    profileContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      // paddingTop: hp(5),
      flexDirection: 'row',
      // justifyContent: 'center',
      alignItems: 'center',
      marginBottom: -hp(2),
    },
    workContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      paddingTop: hp(2),
    },
    headerInitialText: {
      alignSelf: 'center',
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },

    titleText: {
      fontSize: hp(2.4),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      width: wp(40),
    },
    nameText: {
      fontSize: hp(2.4),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },
    priceText: {
      fontSize: hp(2.4),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      textAlign: 'right',
    },
    categoryText: {
      color: theme.color.textBlack,
      fontSize: hp(2),
      width: wp(40),
    },
    workHistoryText: {
      color: theme.color.textBlack,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.semiBoldFamily,
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    customInput: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      // width: hp(5),
    },
    containerStyle: {
      width: wp(36),
      borderColor: theme.color.dividerColor,
    },
    modalTitle: {
      zIndex: 101,
      color: theme.color.textBlack,
      alignSelf: 'center',
      borderBottomWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
      paddingBottom: hp(2),
      marginBottom: hp(2),
      width: hp(45),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingRight: hp(1),
      paddingLeft: hp(1),
    },
    textFieldTitle: {
      fontSize: theme.size.small,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
    },
    errorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: -hp(3.5),
    },

    aboutText: {
      color: theme.color.textBlack,
      fontSize: hp(2.2),
      fontFamily: theme.fontFamily.semiBoldFamily,
      marginBottom: hp(1),
    },
    noteText: {
      fontSize: hp(2.4),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    experienceText: {
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      marginTop: hp(1),
      marginBottom: hp(2),
    },
    reviewText: {
      marginTop: hp(1),
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
    },
    employeedText: {
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      paddingLeft: hp(2),
      marginTop: hp(1),
      marginBottom: hp(1),
    },
    responseText: {
      marginTop: hp(3),
      marginBottom: hp(3),
      color: theme.color.textBlack,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    iconContainer: {
      width: hp(4),
      height: hp(4),
      borderColor: theme.color.dividerColor,
      borderWidth: hp(0.1),
      justifyContent: 'center',
      borderRadius: hp(1),
      alignItems: 'center',
      marginLeft: hp(0.2),
    },
    imageStyle: {
      backgroundColor: theme.color.dividerColor,
      width: wp(15),
      height: hp(8),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: hp(1.5),
      flexDirection: 'row',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignContent: 'center',
    },
    headerLastText: {
      fontSize: theme.size.xLarge,
      color: theme.color.backgroundColor,
      textAlign: 'center',
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
      height: hp(15),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    headerColor: theme.color.textWhite,
    container: {
      flexGrow: 1,
      paddingHorizontal: hp(1),
    },
    profileImage: {
      height: wp(14),
      width: wp(14),
      borderRadius: hp(10),
      borderWidth: hp(0.3),
      marginRight: hp(2),
      alignSelf: 'center',
      borderColor: theme.color.dividerColor,
      backgroundColor: theme.color.textBlack,
      // padding: 20,
    },
    thumbStyle: {
      height: hp(11),
      width: hp(11),
      borderRadius: hp(16),
      borderWidth: hp(0.75),
      alignSelf: 'center',
      borderColor: '#3DB249',
      backgroundColor: '#3DB249',
      // padding: 20,
    },
    workImage: {
      height: hp(5),
      width: hp(5),
      borderRadius: hp(1),
      borderWidth: hp(0.75),
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: theme.color.dividerColor,
      backgroundColor: theme.color.dividerColor,
      // padding: 20,
    },
    dialogStyle: {
      justifyContent: 'space-between',
    },
    homeText: {
      fontSize: theme.size.large,
    },
    saveChangesButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      // padding: hp(2.75),
      width: wp(50),
      height: hp(6.5),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
    },

    saveChangesButtonText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
    },

    profileButton: {
      margin: hp(1),
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: wp(40),
      height: hp(6),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.headerBackgroundColor,
    },
    iconHeaderContainer: {width: '10%', paddingLeft: hp(1)},
    headerTitleContainer: {
      flexDirection: 'row',
      width: '90%',
      alignSelf: 'center',
      justifyContent: 'center',
      alignContent: 'center',
    },
    buttonContainer: {
      justifyContent: 'space-between',
      flexDirection: 'column',
      justifyContent: 'center',
      alignSelf: 'center',
      padding: hp(3),
    },
    formButtonContainer: {
      justifyContent: 'space-between',
      flexDirection: 'row',
      // padding: hp(3),
    },
    chatButton: {
      width: hp(40),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: hp(1),
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    responseButton: {
      width: hp(22),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: '#3DB249',
    },
    cancelModalButton: {
      width: hp(19),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: theme.color.dividerColor,
    },
    acceptModalButton: {
      width: hp(19),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: 'red',
    },
    okButton: {
      width: hp(18),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      backgroundColor: theme.color.textBlack,
    },
    textFieldTitle: {
      fontSize: theme.size.medium,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      paddingLeft: -hp(8),
    },
    submitButton: {
      flexGrow: 1,
      width: hp(35),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      backgroundColor: theme.color.textBlack,
    },
    cancelButton: {
      width: hp(19),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.dividerColor,
      backgroundColor: theme.color.dividerColor,
    },
    inviteButton: {
      width: hp(40),
      height: hp(6.5),
      marginBottom: hp(1),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.03),
      borderColor: theme.color.textBlack,
      backgroundColor: theme.color.textWhite,
    },
    inviteFormButton: {
      width: hp(19),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.03),
      borderColor: theme.color.textBlack,
      backgroundColor: theme.color.textBlack,
    },
    activeButton: {
      width: wp(25),
      height: hp(4.5),
      // marginRight: hp(5),
      borderRadius: hp(1),
      justifyContent: 'center',
      marginTop: hp(2),
      alignItems: 'center',
      borderWidth: hp(0.03),
      borderColor: theme.color.textBlack,
      backgroundColor: theme.color.textWhite,
      alignSelf: 'flex-end',
    },
    headetLastContainer: {
      marginRight: hp(2),
    },
    chatText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    activeText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
      textTransform: 'capitalize',
    },
    inviteText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
    },

    loginButton: {
      width: hp(10),
      height: hp(2.5),
      borderRadius: hp(1),
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    starContainer: {
      // flexGrow: 1,
      paddingLeft: hp(0.5),
      paddingTop: hp(0.5),
      paddingBottom: hp(0.5),
      justifyContent: 'flex-start',
      alignItems: 'center',
      flexDirection: 'row',
    },
    textStyle: {
      textAlign: 'center',
      fontSize: hp(2),
      paddingLeft: hp(2),
      fontFamily: theme.fontFamily.boldFamily,
      color: '#FFB627',
    },
    starImageStyle: {
      width: hp(2.5),
      height: hp(2.5),
      resizeMode: 'cover',
    },
    customRatingBarStyle: {
      justifyContent: 'center',
      flexDirection: 'row',
    },
    starSize: hp(3),
  });
  return styles;
};
export default createStyles;
