import {StyleSheet} from 'react-native';
import {hp, wp} from '../../util';

const createStyles = theme => {
  const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: theme.color.textWhite,
    },
    activityView: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyMessageStyle: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.semiBoldFamily,
      marginTop: hp(15),
      textAlignVertical: 'center',
    },
    subContainer: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: hp(3),
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    profileConatiner: {
      height: hp(12),
      flexDirection: 'row',
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
      alignItems: 'center',
    },
    workHistoryContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      marginTop: hp(1),
    },
    nameContainer: {
      justifyContent: 'flex-start',
      paddingLeft: hp(2),
    },
    aboutContainer: {
      paddingLeft: hp(2),
      paddingTop: hp(2),
      height: hp(15),
      flexGrow: 1,
    },
    historyText: {
      // justifyContent: 'flex-start',
      paddingLeft: hp(2),
      paddingTop: hp(2),
      fontSize: hp(2.2),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },
    workContainer: {
      justifyContent: 'flex-start',
      paddingHorizontal: hp(2),
      paddingRight: hp(8),
      flexGrow: 1,
    },
    headerInitialText: {
      alignSelf: 'center',
      fontSize: hp(3),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },

    nameText: {
      fontSize: hp(2.4),
      color: theme.color.textBlack,
      fontFamily: theme.fontFamily.boldFamily,
    },
    categoryText: {
      color: theme.color.textBlack,
      fontSize: hp(2.4),
    },
    workHistoryText: {
      color: theme.color.textBlack,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.semiBoldFamily,
    },
    loginInputText: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
    },
    customInput: {
      fontSize: theme.size.xsmall,
      fontFamily: theme.fontFamily.mediumFamily,
      // width: hp(5),
    },
    containerStyle: {
      width: wp(36),
      borderColor: theme.color.dividerColor,
    },
    dropdownContainerStyle: {
      paddingLeft: hp(0.5),
      width: wp(74),
    },
    textFieldTitle: {
      fontSize: theme.size.small,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
      marginTop: hp(1),
    },
    timeFieldTitle: {
      fontSize: theme.size.small,
      textAlign: 'left',
      paddingLeft: hp(1.5),
      fontFamily: theme.fontFamily.boldFamily,
      marginTop: hp(2),
    },
    dropdownErrorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: -hp(2),
    },
    errorText: {
      fontSize: theme.size.xsmall,
      color: theme.color.textRed,
      marginHorizontal: wp(3),
      marginTop: hp(0.5),
    },
    modalTitle: {
      color: theme.color.textBlack,
      fontSize: hp(2.4),
      fontFamily: theme.fontFamily.boldFamily,
      alignSelf: 'center',
      borderBottomWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
      paddingBottom: hp(2),
      marginBottom: hp(2),
      width: hp(45),

      textAlign: 'center',
    },
    aboutText: {
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
      marginTop: hp(0.5),
      width: wp(84),
    },
    experienceText: {
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
    },
    descriptionText: {
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.mediumFamily,
    },
    responseText: {
      marginTop: hp(3),
      marginBottom: hp(3),
      color: theme.color.textGray,
      fontSize: hp(2),
      fontFamily: theme.fontFamily.semiBoldFamily,
      textAlign: 'center',
      alignSelf: 'center',
    },
    modalOKbutton: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    iconContainer: {
      width: hp(4),
      height: hp(4),
      borderColor: theme.color.dividerColor,
      borderWidth: hp(0.1),
      justifyContent: 'center',
      borderRadius: hp(1),
      alignItems: 'center',
      marginLeft: hp(1),
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignContent: 'center',
    },
    headerLastText: {
      fontSize: theme.size.xLarge,
      color: theme.color.backgroundColor,
      textAlign: 'center',
    },
    headerContainerStyle: {
      borderBottomColor: theme.color.textWhite,
      backgroundColor: theme.color.textWhite,
      height: hp(15),
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: hp(2),
    },
    headerColor: theme.color.textWhite,
    container: {
      flexGrow: 1,
      paddingHorizontal: hp(1),
    },
    imgStyle: {
      height: wp(17),
      width: wp(17),
      borderRadius: hp(30),
      borderWidth: hp(0.5),
      // alignSelf: 'center',
      borderColor: theme.color.dividerColor,
      // backgroundColor: theme.color.textBlack,
      // padding: 20,
    },
    thumbStyle: {
      height: hp(11),
      width: hp(11),
      borderRadius: hp(16),
      borderWidth: hp(0.75),
      alignSelf: 'center',
      borderColor: '#3DB249',
      backgroundColor: '#3DB249',
      // padding: 20,
    },
    workImage: {
      height: hp(5),
      width: hp(5),
      borderRadius: hp(1),
      borderWidth: hp(0.75),
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: theme.color.dividerColor,
      backgroundColor: theme.color.dividerColor,
      // padding: 20,
    },
    dialogStyle: {
      justifyContent: 'space-between',
    },
    inviteModal: {
      marginTop: hp(3),
      height: hp(90),
    },
    homeText: {
      fontSize: theme.size.large,
    },
    saveChangesButton: {
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      // padding: hp(2.75),
      width: wp(50),
      height: hp(6.5),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.dividerColor,
    },

    saveChangesButtonText: {
      fontSize: theme.size.medium,
      fontFamily: theme.fontFamily.boldFamily,
    },

    profileButton: {
      margin: hp(1),
      alignSelf: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      width: wp(40),
      height: hp(6),
      borderRadius: hp(5),
      borderWidth: hp(0.1),
      borderColor: theme.color.headerBackgroundColor,
    },
    iconHeaderContainer: {width: '10%', paddingLeft: hp(1)},
    headerTitleContainer: {
      flexDirection: 'row',
      width: '90%',
      alignSelf: 'center',
      justifyContent: 'center',
      alignContent: 'center',
    },
    buttonContainer: {
      justifyContent: 'space-between',
      flexDirection: 'row',
      padding: hp(3),
    },
    formButtonContainer: {
      justifyContent: 'space-between',
      flexDirection: 'row',
      marginTop: hp(2),
    },
    sendHireInviteButton: {
      width: wp(42),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    responseButton: {
      width: hp(22),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignSelf: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: '#3DB249',
      backgroundColor: '#3DB249',
    },
    cancelButton: {
      width: wp(36),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.dividerColor,
      backgroundColor: theme.color.dividerColor,
    },
    ChatButton: {
      width: wp(42),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.08),
      borderColor: theme.color.textBlack,
      backgroundColor: theme.color.textWhite,
    },
    inviteFormButton: {
      width: wp(36),
      height: hp(6.5),
      borderRadius: hp(1),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.03),
      borderColor: theme.color.textBlack,
      backgroundColor: theme.color.textBlack,
    },
    sendHireInviteButtonText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
    ChatButtonText: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textBlack,
    },

    loginButton: {
      width: hp(10),
      height: hp(2.5),
      borderRadius: hp(1),
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: hp(0.01),
      borderColor: theme.color.textWhite,
      backgroundColor: theme.color.textBlack,
    },
    text: {
      fontSize: theme.size.small,
      fontFamily: theme.fontFamily.semiBoldFamily,
      color: theme.color.textWhite,
    },
  });
  return styles;
};
export default createStyles;
